FROM ubuntu:22.04
COPY . /myapp
WORKDIR /myapp
RUN apt update
RUN apt install python3.10 -y
RUN apt install python3-pip -y
RUN pip3.10 install flask
RUN pip3.10 install dash
RUN pip3.10 install dash_leaflet
RUN pip3.10 install thread6
RUN pip3.10 install jsons
EXPOSE 1010
CMD python3.10 app.py